### ISSUE TITLE
Requirement for vit-based work

### ISSUE THREAD

**Issue by YilinGao-SHU** [LMJJJJJJ/nn-visualizer#2]
Thanks for your solid work! I wonder if you have try the visualizer on Vit based model? If some extra work is needed here?

**Comment by LMJJJJJJ** [comment]
Hi there! Thank you for your positive feedback! Currently, I haven't explored applying this method to vit-based models specifically. However, following the approach in the paper, it should be feasible to use the regional features from vit as input to the visualizer, allowing for experimental results on vit models. Thanks again for your interest!

**Comment by YilinGao-SHU** [comment]
Thanks for your replay~发送自我的盖乐世
-------- 原始信息 --------发件人： Mingjie Li ***@***.***> 日期: 2024/1/17  17:10  (GMT+08:00) 收件人： LMJJJJJJ/nn-visualizer ***@***.***> 抄送： YilinGao-SHU ***@***.***>, Author ***@***.***> 主题： Re: [LMJJJJJJ/nn-visualizer] Requirement for vit-based work (Issue #2) 
Hi there! Thank you for your positive feedback! Currently, I haven't explored applying this method to vit-based models specifically. However, following the approach in the paper, it should be feasible to use the regional features from vit as input to the visualizer, allowing for experimental results on vit models. Thanks again for your interest!
